development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
<<<<<<< HEAD
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
=======
  url: redis://localhost:6379/1
>>>>>>> origin/master
  channel_prefix: my_first_rails_app_production
